### ISSUE TITLE
software installation

### ISSUE THREAD

**Issue by 1997mohan** [simsausaurabh/Automatic-Lock-System#1]
please can you mention which raspberry pi OS you've used and also the opencv version

**Comment by simsausaurabh** [comment]
I didn't use raspberry, it solely runs on Ubuntu 16.04 LTS OS. I have used Opencv2. Please feel free to ask anything.

**Comment by 1997mohan** [comment]
i want to this as a project using raspberry pi 3 model B then what should i do now?

**Comment by simsausaurabh** [comment]
You will need tensor flow, transfer learning. You will need to train the data-set onto your laptop/pc then dump the the repository created onto the raspberry pi.

**Comment by 1997mohan** [comment]
is there any repository you know or please guide me in this project i have to do face recognition door lock using raspberry pi 3. first i'm completely new to this environment  i searched many repositories and all i ended up with the errors based on compatibility problems with the OS in my raspberry pi today's raspberry pi OS became more advanced and opencv is also upgraded when i use those repositories which they have build say they have build using opencv 2.4.9 or something i cannot use that since i'm using 3.4.1 so i have to downgrade if u have any known repository please refer that to me

**Comment by simsausaurabh** [comment]
For further queries, I can suggest you my friend who has done the same type of problem: 201551012@iiitvadodara.ac.in(Gmail)

**Comment by 1997mohan** [comment]
thankyou my friend
